name: Notify when PR is merged to main or develop branch

on:
  pull_request:
    branches: [ "*" ]


jobs:
  auto_send_notification:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      # Notify Slack 
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: curl -o ./.github/workflows/slackNotification.send https://gist.githubusercontent.com/tonynguyenit18/7bb4e833ef507822ef97ac5cdef9192a/raw/slackNotification.send && chmod +x ./.github/workflows/slackNotification.send && ./.github/workflows/slackNotification.send $SLACK_WEBHOOK_URL https://github.com/tonynguyenit18/test-notification-git-action test_notification